Add mutation for create Good Practice
idmc-labs/gidd-server pull request #17
Opened 2022-12-02 09:09 UTC by Rup-Narayan-Rajbanshi

- Addresses Good Practice

## Changes
 - Add mutation for create Good Practice
- Added Hcaptcha
- Modified Admin table names and App names
- Added language translation
- Setup test case

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-12-05 05:48 UTC, thenav56 requested changes
Looks good. Some suggestions.

2022-12-05 05:48 UTC, thenav56 commented on apps/good_practice/apps.py
> +    verbose_name = "Global Repository of Good Practices"
Missing translation.

2022-12-05 05:48 UTC, thenav56 commented on apps/good_practice/models.py
> +    )
What is the behavior for this? @AdityaKhatri @Rup-Narayan-Rajbanshi

2022-12-05 05:48 UTC, thenav56 commented on apps/good_practice/mutations.py
> +                image=image,
Does this work?

2022-12-05 05:48 UTC, thenav56 commented on apps/good_practice/mutations.py
> +            obj = GoodPractice.objects.create(
Let's use a serializer for this.

2022-12-05 05:48 UTC, thenav56 commented on apps/good_practice/mutations.py
> +        captcha: Optional[str] = None,
Let's nest this, maybe define GoodPracticeInputType.

Add a TODO note for create auto-type generator. For ref look into this: https://github.com/strawberry-graphql/strawberry/pull/137/files

2022-12-05 05:48 UTC, thenav56 commented on apps/good_practice/tests/factories.py
> +    )
Maybe do this in the individual tests instead. Which will be few.
This will create a file for each factory created.

2022-12-05 05:48 UTC, thenav56 commented on config/tests.py
> +def assert_num_queries(n: int, *, using=DEFAULT_DB_ALIAS):
Is this used?

2022-12-05 05:48 UTC, thenav56 commented on apps/good_practice/tests/test_mutations.py
> +# WIP
Reason?

2022-12-08 04:41 UTC, Rup-Narayan-Rajbanshi commented on apps/good_practice/models.py
> +    )
@thenav56 , When a public submits a good practice it should be true which is immutable.

2022-12-08 15:16 UTC, thenav56 commented on apps/good_practice/models.py
> +    )
Let's add this as [help_text](https://docs.djangoproject.com/en/4.1/ref/models/fields/#help-text) there. Don't forget the translation :P

2022-12-15 07:58 UTC, thenav56 commented
@bimal125 @Rup-Narayan-Rajbanshi
We have all these changes in this PR right? https://github.com/idmc-labs/gidd-server/pull/19

2022-12-15 08:41 UTC, closed without merging