Add forgot password feature
idmc-labs/gidd-server pull request #18
Opened 2022-12-05 08:41 UTC by Rup-Narayan-Rajbanshi

- Addresses #14 
- Depends on #19 

## Changes
- Add reset password feature

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-12-05 11:23 UTC, bimal125 requested changes

2022-12-05 11:23 UTC, bimal125 commented on apps/common/views.py
> +                for user in associated_users:
There should not be more than one user with same email

2022-12-05 11:23 UTC, bimal125 commented on apps/common/views.py
> +                        return HttpResponse('Invalid header found.')
How BadHeaderError appears as an exception when sending an email, we should send cleaned header instead.

2022-12-14 08:34 UTC, thenav56 requested changes

2022-12-14 08:34 UTC, thenav56 commented on apps/common/tasks.py
> +    send_mail(**email_data)
Let's use define something like this

```python3
from django.conf import settings
from django.template import loader

from django.core.mail import EmailMultiAlternatives


# TODO: Move this to utils/mail.py
def base_send_mail(
    subject_template_name,
    email_html_template_name,
    email_text_template_name,
    context,
    from_email,
    to_email,
):
    """
    Send a django.core.mail.EmailMultiAlternatives to `to_email`.
    Renders provided templates and send it to to_email
    Low level, Don't use this directly
    """
    # Subject
    subject = ''.join(
        # Email subject *must not* contain newlines
        loader.render_to_string(
            subject_template_name,
            context,
        ).splitlines
    )
    # Body
    html_content = loader.render_to_string(email_html_template_name, context)
    text_content = loader.render_to_string(email_text_template_name, context)
    # Email message
    email_message = EmailMultiAlternatives(
        subject,
        text_content,  # Plain text
        from_email,
        [to_email],
    )
    # HTML
    email_message.attach_alternative(html_content, "text/html")
    # Send email
    email_message.send()


# TODO: Move this to utils/mail.py
def send_mail(
    subject_template_name,
    email_html_template_name,
    email_text_template_name,
    user,
    context=None,
):
    """
    A generic send mail function
    - With default context values
    - Single receipient
    """
    if context is None:
        context = {}

    context.update({
        'domain': settings.APP_DOMAIN,
        'user': user,
    })

    base_send_mail(
        subject_template_name,
        email_html_template_name,
        email_text_template_name,
        context,
        settings.DEFAULT_FROM_EMAIL,
        user.email,
    )


def send_password_reset_mail(user):
    send_mail(
        'registration/password_reset/subject.txt',
        'registration/password_reset/body.txt',
        'registration/password_reset/body.html',
        user,
    )
```

Then define the templates
- `registration/password_reset/subject.txt`
  ```text
  Password Reset
  ```

- `registration/password_reset/body.txt`
  ```text
    <-- Define the message and url link here in plan text-->
  ```

- `registration/password_reset/body.html`
  ```html
   {% extends "email/generic_email.html" %}
   {% block content %}
      <-- Define the message and url link here in html format-->
   {% endblock %}
  ```

2022-12-14 08:34 UTC, thenav56 commented on config/urls.py
> +        template_name='password_reset_complete.html'), name='password_reset_complete'),
This should be enough
```suggestion
    path(
        r'^password/reset/<uidb64>/<token>/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('login'),
            ),
        name='password_reset_confirm'
    ),
```

2022-12-14 08:34 UTC, thenav56 commented on config/settings.py
> +    DOMAIN_URL=(str, 'http://localhost:7000'),
Let's use APP_DOMAIN instead of `_URL` as this is not a URL.
```suggestion
    APP_DOMAIN=(str, 'http://localhost:7000'),
```

2022-12-14 08:34 UTC, thenav56 commented on config/settings.py
> +    EMAIL_BACKEND = 'django_ses.SESBackend'
Let's not use AWS_S3 here as this is AWS_SES,

Let's do something like this
```suggestion
if env('USE_AWS_SES'):
    EMAIL_BACKEND = 'django_ses.SESBackend'
    AWS_SES_REGION_NAME = env('AWS_SES_REGION_NAME')
    AWS_SES_ACCESS_KEY_ID = env('AWS_SES_ACCESS_KEY_ID')
    AWS_SES_SECRET_ACCESS_KEY = env('AWS_SES_SECRET_ACCESS_KEY')
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
```

2022-12-14 08:34 UTC, thenav56 commented on config/settings.py
> +    DEFAULT_FROM_EMAIL=(str, None),
```suggestion
    DEFAULT_FROM_EMAIL=(str, None),
    USE_AWS_SES=(bool, False),
    # -- If not provided IAM Role will be used
    AWS_SES_REGION_NAME=(str, None),
    AWS_SES_ACCESS_KEY_ID=(str, None),
```

2022-12-20 09:28 UTC, thenav56 requested changes
Looks good. We will need a captcha here as well.

2022-12-20 09:28 UTC, thenav56 commented on docker-compose.yml
> +  redis-data:
We don't need this right?
```suggestion
```

2022-12-21 08:08 UTC, bimal125 approved these changes

2022-12-21 10:03 UTC, thenav56 approved these changes

2022-12-26 07:47 UTC, thenav56 approved these changes

2022-12-26 07:49 UTC, bimal125 approved these changes

2022-12-26 07:54 UTC, merged