Feature/setup validation errors
idmc-labs/gidd-server pull request #19
Opened 2022-12-15 06:45 UTC by bimal125

## Changes

* Add good practice mutation

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-12-15 08:15 UTC, bewakes commented on apps/good_practice/tests/factories.py
> +class GoodFactoryFactory(DjangoModelFactory):
Perhaps the name should be `GoodPracticeFactory`? I am not entirely sure though.

2022-12-15 08:41 UTC, thenav56 requested changes
Few comments.
Also, the test seems to be WIP.

2022-12-15 08:41 UTC, thenav56 commented on apps/good_practice/models.py
> +        help_text=_('When a public submits a good practice it should be true which is immutable.'),
```suggestion
        help_text=_('It indicates if a good practice is submitted without authentication'),
```

2022-12-15 09:04 UTC, bewakes approved these changes

2022-12-16 05:17 UTC, k9845 approved these changes

2022-12-16 05:23 UTC, k9845 approved these changes

2022-12-16 05:23 UTC, k9845 commented on apps/good_practice/tests/factories.py
> +class GoodFactoryFactory(DjangoModelFactory):
@bimal125 look into this.

2022-12-16 10:26 UTC, thenav56 approved these changes
LGTM.

2022-12-26 04:39 UTC, thenav56 approved these changes

2022-12-26 05:51 UTC, merged