Sanitize the text field for good practice mutation
idmc-labs/gidd-server pull request #22
Opened 2022-12-23 05:31 UTC by Rup-Narayan-Rajbanshi

- Depends on #18 

## Changes
- Sanitize text field for good practice table
- Added a generic method for sanitizing text field except translated text field

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-12-26 06:23 UTC, thenav56 requested changes
Looks good. Few suggesstions.

2022-12-26 06:23 UTC, thenav56 commented on apps/country/models.py
> +import config.custom_fields  # noqa F401
Let's add a NOTE as well on why we are doing this.

2022-12-26 06:23 UTC, thenav56 commented on config/custom_fields.py
> +    # TODO: find the way to override custom field in modeltranslation
We can also do something like this
```python3
from modeltranslation.utils import build_localized_fieldname
from django.conf import settings


def clean_text_fields(obj, *fields):
    for field in fields:
        for lang, _ in settings.LANGUAGES:
            lang_field = build_localized_fieldname(field, lang)
            original_value = getattr(obj, lang_field, '')
            sanitized_value = sanitizer.sanitize(original_value)
            setattr(obj, lang_field, sanitized_value)
```

2022-12-26 06:23 UTC, thenav56 commented on config/custom_fields.py
> +django.db.models.TextField.get_db_prep_value = get_db_prep_value
Let's remove this if not used to avoid confusion.

2022-12-29 04:18 UTC, thenav56 requested changes
LGTM. Few changes

2022-12-29 04:18 UTC, thenav56 commented on config/custom_fields.py
> +            print(original_value)
```suggestion
```

2022-12-29 04:18 UTC, thenav56 commented on apps/good_practice/tests/test_mutations.py
> +                # descriptionEn='some text description en',
Let's remove this

2022-12-29 04:42 UTC, bimal125 approved these changes

2022-12-29 04:43 UTC, thenav56 approved these changes

2022-12-29 05:08 UTC, merged