Feature/gidd good practice
idmc-labs/gidd-server pull request #28
Opened 2023-03-02 05:43 UTC by Rup-Narayan-Rajbanshi

- Addresses https://github.com/idmc-labs/idmc-website-components/issues/44

## Changes
- Make required field optional, add fields, rename fields, 

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2023-03-02 10:06 UTC, thenav56 requested changes

2023-03-02 10:54 UTC, thenav56 requested changes

2023-03-02 10:54 UTC, thenav56 commented on apps/good_practice/models.py
> +    under_review = models.BooleanField(default=False)
Let's use the migration runPython to set False for existing entries. For new ones let's use default=True and don't let client assign this value.

2023-03-02 10:54 UTC, thenav56 commented on apps/good_practice/mutations.py
> +    # stage: Optional[str]
```suggestion
```

2023-03-02 10:54 UTC, thenav56 commented on apps/good_practice/tests/test_mutations.py
> +            print(response)
```suggestion
```

2023-03-07 09:55 UTC, bimal125 commented on apps/good_practice/models.py
> +    under_review = models.BooleanField(default=False)
@thenav56  changed logic accordingly

2023-03-07 09:57 UTC, bimal125 approved these changes

2023-03-07 10:53 UTC, thenav56 approved these changes
It's okay to merge now. But let's do this in future PR

- Let's try to use Enum instead. Maybe define a default value here instead. https://github.com/idmc-labs/gidd-server/pull/28#discussion_r1122851026
- Rename `createGoodPractice` -> `publicCreateGoodPractice`

2023-03-07 11:34 UTC, merged