Add a new field success_factor, filter and fixtures in Good Practice
idmc-labs/gidd-server pull request #40
Opened 2024-01-29 05:19 UTC by saauravsapkota

- Addresses xxxxxx (eg: #1)
- Depends on xxxxxx (eg: #1)

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-01-29 10:40 UTC, Rup-Narayan-Rajbanshi reviewed
@saauravsapkota Lets change the fixture file name from success_factors_fixture.json to success_factors.json

2024-01-30 05:27 UTC, thenav56 requested changes
Looks good. Few comments

2024-01-30 05:27 UTC, thenav56 commented on apps/good_practice/admin.py
> +        return ", ".join([item.name for item in obj.success_factor.all()])
Let's add a custom queryset with these fields prefetched.

2024-01-30 05:27 UTC, thenav56 commented on apps/good_practice/dataloaders.py
> +            _map[good_practice.id].append(success_factor)
We have N+1 issue here.
Let's use `GoodPractice.success_factor.through.objects` for fetch `good_practice_id` and `success_factor`.

Something like this
```python
qs = GoodPractice.success_factor.through.objects.filter(good_practice__in=keys).select_related('success_factor')

for row in qs:
  _map[qs.good_practice_id].append(qs.success_factor)
```

2024-01-30 05:27 UTC, thenav56 commented on apps/good_practice/schema.py
> +            .distinct("success_factor__name")
Let's use id for distinct

2024-01-30 05:27 UTC, thenav56 commented on apps/good_practice/types.py
> +    ) -> Optional[List[SuccessFactorType]]:
Let's return with empty array if empty
```suggestion
    ) -> List[SuccessFactorType]:
```

2024-01-30 05:27 UTC, thenav56 commented on apps/good_practice/types.py
> +    success_factor: Optional[List[SuccessFactorType]]
Let's return with empty array if empty
```suggestion
    success_factor: List[SuccessFactorType]
```

2024-01-30 05:27 UTC, thenav56 commented on .gitignore
> +sitecus
Let's remove duplicates.

Also, is there any reason for these?
```
typings/
pyrightconfig.json
response.json
```

2024-01-30 05:27 UTC, thenav56 commented on apps/good_practice/fixtures/success_factors.json
> +    "name_fr": null
Can you check if this will overwrite the values with `null` in the database for the field `name_fr`? Let's remove that if not required.
We want to avoid overwriting data provided by users.

2024-01-31 10:35 UTC, thenav56 approved these changes

2024-02-01 04:22 UTC, merged